name: ci
on:
  pull_request:
  push:
    branches:
      - master
      - main
jobs:
  build-linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Vet
        run: make vet

      - name: Test
        run: make test

      - uses: codecov/codecov-action@v1

      - name: goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --snapshot --skip-publish --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
